### ISSUE TITLE
no symbol section

### ISSUE THREAD

**Issue by mrbardia72** [nikolaydubina/go-binsize-treemap#6]
/bin$ go tool nm -size api
reading api: no symbol section
reading api: no symbols

**Comment by nikolaydubina** [comment]
could you share which repo is this? need to repro.

are you building with cgo? could you share platform details?

**Comment by vincentbernat** [comment]
This can happen if you compile with `-ldflags "-w -s"`

**Comment by neophiliac** [comment]
I'm building with `CGO_ENABLED=0` and no ldflags specified, and I get the same errors. Sorry, private repo. I'll try it on some other repos and add another comment if I find one that you can use to see this problem.

**Comment by nikolaydubina** [comment]
yeah, got to fix this. other binsize analysers can handle that, but this tool panics

```
go tool nm -size main  | go-binsize-treemap > binsize.svg   
reading main: no symbol section
reading main: no symbols
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/nikolaydubina/treemap.SumSizeImputer.ImputeSizeNode({0x0?}, {0x0?, 0x0?, {0x0?, 0x3?}}, {0x0, 0x0})
        /Users/nikolaydubina/go/pkg/mod/github.com/nikolaydubina/treemap@v1.2.5/size_imputer.go:32 +0x20c
github.com/nikolaydubina/treemap.SumSizeImputer.ImputeSize(...)
        /Users/nikolaydubina/go/pkg/mod/github.com/nikolaydubina/treemap@v1.2.5/size_imputer.go:11
main.main()
        /Users/nikolaydubina/go/pkg/mod/github.com/nikolaydubina/go-binsize-treemap@v0.2.3/main.go:74 +0x43c
```
